CREATE TABLE IF NOT EXISTS  `publicidad` (
 `id` SMALLINT( 3 ) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT ,
 `url` VARCHAR( 250 ) DEFAULT NULL ,
 `image` VARCHAR( 150 ) DEFAULT NULL ,
 `position` SMALLINT( 3 ) DEFAULT NULL ,
 `status` VARCHAR( 15 ) DEFAULT NULL ,
PRIMARY KEY (  `id` )
) ENGINE = INNODB DEFAULT CHARSET = latin1 AUTO_INCREMENT =1;